// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Porcupine3API.DBContexts;

#nullable disable

namespace Porcupine3API.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20230605133244_procupine")]
    partial class procupine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Porcupine3API.Models.GroupM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Group1"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Group2"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Group3"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Group4"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Group5"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Group6"
                        });
                });

            modelBuilder.Entity("Porcupine3API.Models.PermissionsM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            GroupID = 1,
                            UserID = 1
                        },
                        new
                        {
                            ID = 2,
                            GroupID = 1,
                            UserID = 2
                        },
                        new
                        {
                            ID = 3,
                            GroupID = 2,
                            UserID = 1
                        },
                        new
                        {
                            ID = 4,
                            GroupID = 2,
                            UserID = 5
                        },
                        new
                        {
                            ID = 5,
                            GroupID = 3,
                            UserID = 3
                        },
                        new
                        {
                            ID = 6,
                            GroupID = 3,
                            UserID = 4
                        },
                        new
                        {
                            ID = 7,
                            GroupID = 4,
                            UserID = 4
                        });
                });

            modelBuilder.Entity("Porcupine3API.Models.UserM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "mmcd@email.com",
                            Name = "Marly",
                            Surname = "McDonnell"
                        },
                        new
                        {
                            ID = 2,
                            Email = "anewton@email.com",
                            Name = "Isaac",
                            Surname = "Newton"
                        },
                        new
                        {
                            ID = 3,
                            Email = "agarcia@email.com",
                            Name = "Isabella",
                            Surname = "Garcia"
                        },
                        new
                        {
                            ID = 4,
                            Email = "pcruz@email.com",
                            Name = "Penelope",
                            Surname = "Cruz"
                        },
                        new
                        {
                            ID = 5,
                            Email = "ttickle@email.com",
                            Name = "Tess",
                            Surname = "Tickle"
                        },
                        new
                        {
                            ID = 6,
                            Email = "sreed@email.com",
                            Name = "Spencer",
                            Surname = "Reed"
                        },
                        new
                        {
                            ID = 7,
                            Email = "drossi@email.com",
                            Name = "David",
                            Surname = "Rossi"
                        },
                        new
                        {
                            ID = 8,
                            Email = "ahotchner@email.com",
                            Name = "Aaron",
                            Surname = "Hotchner"
                        },
                        new
                        {
                            ID = 9,
                            Email = "mfreeman@email.com",
                            Name = "Morgan",
                            Surname = "Freeman"
                        },
                        new
                        {
                            ID = 10,
                            Email = "tlasso@email.com",
                            Name = "Ted",
                            Surname = "Lasso"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
